# site settings
title: CCB
subtitle: DIRECTORS
email: josh@jpax.tv
description: Film intersects with advertising intersects with brand.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
author: Josh Parkhill
city: New York
state: NY
zip_code: 1000
country: United States of America
lang: en
# phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  #GitHub: https://github.com/andrewbanchich
  #GitLab:
  # Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram: instagram.com/jptv.media
  LinkedIn: https://www.linkedin.com/in/jptvmedia
  Bluesky: https://bsky.app/profile/parkholer.bsky.social
  Substack: https://jptv.substack.com/
  Website: https://jptv.media

# build settings
markdown: kramdown
permalink: none
comments: false

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
